vich_uploader:
    db_driver: orm

    mappings:
        creation_images:
            uri_prefix: /images/creations
            upload_destination: '%kernel.project_dir%/public/images/creations'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
